toplevel: toolchain, almost

diff --git a/GNUmakefile.am b/GNUmakefile.am
--- a/GNUmakefile.am
+++ b/GNUmakefile.am
@@ -21,6 +21,20 @@ V_ = 0 # $(AM_DEFAULT_VERBOSITY)
 V_0 = 0
 V_1 = 1
 
+# Usage: newest_version $pkg
+# return version number of latest standard package $pkg
+define newest_version
+$(shell \
+    PKG="$(1)";\
+    if [ -f "@abs_top_srcdir@/build/pkgs/$$PKG/package-version.txt" ]; then\
+        echo -n $$PKG-;\
+        cat "@abs_top_srcdir@/build/pkgs/$$PKG/package-version.txt";\
+    else\
+        echo >&2 "Cannot determine latest version of $$PKG.";\
+        echo -n "$$PKG-unknown";\
+    fi;)
+endef
+
 .sagedist:
 	$(MAKE) -C sagedist
 	touch $@
@@ -85,10 +99,20 @@ define upstreampackages
 	$(shell  shopt -s extglob && for i in $(VERSION_ALL); do echo upstream/$${i%.p[0-9]?([0-9])}.tar.bz2; done )
 endef
 
+if DISTUPSTREAM
+# include upstream unless user requests to skip it
+# invoke with make dist DISTFLAGS=tiny
+UPSTREAM_DIST_TRUE=$(if $(filter $(DISTFLAGS),tiny),\#,)
+else
+# dont include upstream unless user requests it
+# invoke with make dist DISTFLAGS=upstream
+UPSTREAM_DIST_TRUE=$(if $(filter $(DISTFLAGS),upstream),,\#)
+endif
+
 .SECONDEXPANSION:
 dist-hook: $$(call upstreampackages)
 	$(MKDIR_P) $(distdir)/upstream
-	cp $+ $(distdir)/upstream
+	$(UPSTREAM_DIST_TRUE)cp $+ $(distdir)/upstream
 
 # add builtin submodule contents to dist (much better)
 @distdir_subs@
@@ -177,12 +201,31 @@ $(INST)/%: STAGETARGET=install
 # no need to install sagelib
 $(INST)/sagelib-builtin: STAGETARGET=stage
 
+# allow system gcc durin toolchain build
+
+# sometimes extra commands need to be injected
+$(INST)/%: EXTRA_COMMANDS=
+
+# bypass dummy gcc for a few packages. done differently
+# bug. use maybe_sage_CC?
+$(INST)/$(FP_mpir) $(INST)/$(FP_mpc) $(INST)/$(FP_mpfr) $(INST)/$(FP_gcc) $(INST)/$(FP_zlib) $(INST)/$(FP_ppl): \
+    EXTRA_COMMANDS=export CC=$(shell which gcc);
+
+# toolchain: build package (if enabled) with toolchain-flags, stamp and forget.
+$(INST)/toolchain_%:
+	[ x$(SAGE_$(call packagename,$*)) = xyes ] && \
+		SAGE_BUILD_TOOLCHAIN=yes $(MAKE) $(INST)/$* && \
+		rm $(INST)/$* || :
+	touch $@
+
+$(INST)/toolchain_%: SAGE_BUILD_TOOLCHAIN=yes
+
 # FIXME: better create symlinks during unpack, not here
 # overly complicated. should really use makefiles... :|
 .SECONDEXPANSION:
-$(INST)/%: $$($$(firstword $$(subst -, ,$$*))_DEPS) $(PHONYDEP) |\
+$(INST)/%: $$(if $(filter $(SAGE_BUILD_TOOLCHAIN),yes),,$$($$(firstword $$(subst -, ,$$*))_DEPS)) |\
            $(PKGSDIR)/% $(SAGE_LOGS) $(INST) $(PKGSDIR) .sagedist
-	@echo "==== staging $* ===="
+	@echo "==== staging $* toolchain: $(SAGE_BUILD_TOOLCHAIN) ===="
 	@path=$(PKGSDIR)/$*; \
 	export CC="@CC@" CFLAGS="@CFLAGS@" \
 	       UNAME="@UNAME@" \
@@ -199,6 +242,7 @@ $(INST)/%: $$($$(firstword $$(subst -, ,$$*))_DEPS) $(PHONYDEP) |\
 	export FILELIST="$(FILELIST)"; \
 	export SAGE_ETC="$(SAGE_ETC)"; \
 	export SAGE_PREFIX="$(SAGE_PREFIX)"; \
+	$(EXTRA_COMMANDS) \
 	$(PIPE) "./spkg-install $(STAGETARGET) $(MAKEOVERRIDES)" 'tee -a $(SAGE_LOGS)/$*.log'; \
 	if [ $$? -ne 0 ]; then \
 		echo $@ failed, deleting; \
@@ -461,6 +505,10 @@ clean-local: @VPATH_BUILD_FALSE@ $(FOREIGN_ALL:%=%-clean)
 
 	rm -f $(LOCKFILE)
 	@VPATH_BUILD_TRUE@rm -rf build
+
+# clean does not really "clean". realclean should
+realclean: clean
+	rm -rf local
 
 bdist-clean: clean
 	@echo "Deleting miscellaneous artifacts generated by build system ..."
