mpc: spkg-install

diff --git a/build/pkgs/mpc/spkg-install b/build/pkgs/mpc/spkg-install
--- a/build/pkgs/mpc/spkg-install
+++ b/build/pkgs/mpc/spkg-install
@@ -6,17 +6,18 @@ if [ "$SAGE_LOCAL" = "" ]; then
     exit 1
 fi
 
-cd src
-
 # Apply patches.  See SPKG.txt for information about what each patch
 # does.
-for patch in ../patches/*.patch; do
-    [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
-    patch -p1 <"$patch"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error applying '$patch'"
-    fi
-done
+( echo "include spkg.mk" | sage-dist-make - patch-stamp ) || exit $?
+cd src
+
+# for patch in ../patches/*.patch; do
+#     [ -r "$patch" ] || continue  # Skip non-existing or non-readable patches
+#     patch -p1 <"$patch"
+#     if [ $? -ne 0 ]; then
+#         echo >&2 "Error applying '$patch'"
+#     fi
+# done
 
 
 # Unset CC and CFLAGS.  This will make mpc use the same configuration
