symmetrica: patches fixed

diff --git a/build/pkgs/symmetrica/spkg-install b/build/pkgs/symmetrica/spkg-install
--- a/build/pkgs/symmetrica/spkg-install
+++ b/build/pkgs/symmetrica/spkg-install
@@ -20,15 +20,16 @@ fi
 CFLAGS="-O2 -g $CFLAGS -fPIC -DFAST -DALLTRUE"
 export CFLAGS
 
+( echo "include spkg.mk" | sage-dist-make - patch-stamp SRC=.) || exit $?
 
 cd src
 
-for patch in $CUR/patches/*.patch; do
-    patch < "$patch"
-    if [ $? -ne 0 ]; then
-        echo >&2 "Error: Patch \"$patch\" failed to apply."
-    fi
-done
+# for patch in $CUR/patches/*.patch; do
+#     patch < "$patch"
+#     if [ $? -ne 0 ]; then
+#         echo >&2 "Error: Patch \"$patch\" failed to apply."
+#     fi
+# done
 
 # Patching the upstream Makefile doesn't make sense,
 # as it has (syntactically) nothing in common with ours.
