sage-bin build system continued

diff --git a/src/bin/env.sh.in b/src/bin/env.sh.in
--- a/src/bin/env.sh.in
+++ b/src/bin/env.sh.in
@@ -1,5 +1,11 @@
 # -*- shell-script -*-
 
+# THIS IS THE WRONG PLACE TO HARDWIRE PATHS
+#
+# environment must be provided within <packagename>/spkg-install.
+# particularly, most parts of this file need to be migrated to
+# sagelib/spkg-install
+
 ###########################################################################
 #
 #  Set environment variables for running Sage.
@@ -112,35 +118,37 @@ resolvelinks() {
     echo "$out"
 }
 
-
-# New value for SAGE_ROOT: either SAGE_ROOT (if given)
-# or a guessed value based on pwd.
-if [ -n "$SAGE_ROOT" ]; then
-    NEW_SAGE_ROOT="$SAGE_ROOT"
-elif [ -f sage -a -d build ]; then
-    NEW_SAGE_ROOT="."
-elif [ -f ../../sage -a -d ../../build ]; then
-    NEW_SAGE_ROOT="../.."
-else
-    # No idea what SAGE_ROOT should be...
-    echo >&2 "Error: You must set the SAGE_ROOT environment variable or run this"
-    echo >&2 "script from the SAGE_ROOT or SAGE_ROOT/local/bin/ directory."
-    return 1
-fi
-
-# Make NEW_SAGE_ROOT absolute
-NEW_SAGE_ROOT=`cd "$NEW_SAGE_ROOT" && pwd -P`
-
-# Sanity check NEW_SAGE_ROOT
-if [ -f "$NEW_SAGE_ROOT/sage" -a -d "$NEW_SAGE_ROOT/build" ]; then
-    :
-else
-    echo >&2 "Error: SAGE_ROOT is set to a bad value:"
-    echo >&2 "SAGE_ROOT=$SAGE_ROOT"
-    echo >&2 "You must correct it or erase it and run this script from the SAGE_ROOT"
-    echo >&2 "or SAGE_ROOT/local/bin/ directory."
-    return 1
-fi
+# this does not make sense. whatever it is supposed to do, this is not the
+# right place (this is sagelib)
+#
+# # New value for SAGE_ROOT: either SAGE_ROOT (if given)
+# # or a guessed value based on pwd.
+# if [ -n "$SAGE_ROOT" ]; then
+#     NEW_SAGE_ROOT="$SAGE_ROOT"
+# elif [ -f sage -a -d build ]; then
+#     NEW_SAGE_ROOT="."
+# elif [ -f ../../sage -a -d ../../build ]; then
+#     NEW_SAGE_ROOT="../.."
+# else
+#     # No idea what SAGE_ROOT should be...
+#     echo >&2 "Error: You must set the SAGE_ROOT environment variable or run this"
+#     echo >&2 "script from the SAGE_ROOT or SAGE_ROOT/local/bin/ directory."
+#     return 1
+# fi
+# 
+# # Make NEW_SAGE_ROOT absolute
+# NEW_SAGE_ROOT=`cd "$NEW_SAGE_ROOT" && pwd -P`
+# 
+# # Sanity check NEW_SAGE_ROOT
+# if [ -f "$NEW_SAGE_ROOT/sage" -a -d "$NEW_SAGE_ROOT/build" ]; then
+#     :
+# else
+#     echo >&2 "Error: SAGE_ROOT is set to a bad value:"
+#     echo >&2 "SAGE_ROOT=$SAGE_ROOT"
+#     echo >&2 "You must correct it or erase it and run this script from the SAGE_ROOT"
+#     echo >&2 "or SAGE_ROOT/local/bin/ directory."
+#     return 1
+# fi
 
 # Warn if NEW_SAGE_ROOT does not equal the old SAGE_ROOT
 if [ "$SAGE_ROOT" != "$NEW_SAGE_ROOT" -a -n "$SAGE_ROOT" ]; then
@@ -223,18 +231,15 @@ if [ 1 = 2 ]; then
 fi
 
 # Setting Sage-related location environment variables.
-export SAGE_LOCAL="@prefix@"
-export SAGE_SHARE="$SAGE_LOCAL/share"
+# export SAGE_LOCAL="@prefix@" (dist)
+# export SAGE_SHARE="$SAGE_LOCAL/share" (dist)
 export SAGE_EXTCODE="$SAGE_SHARE/sage/ext"
-export SAGE_SPKG_INST="$SAGE_LOCAL/var/lib/sage/installed"
 
 # OUCH fixme
-export SAGE_LOGS="@prefix@/../logs/pkgs"
+# export SAGE_LOGS="@prefix@/../logs/pkgs" (dist)
 
 # SAGE_SRC is where the sage/[..]/.pyx are looked for
-export SAGE_SRC="@abs_top_srcdir@/.."
-
-export SAGE_DOC="$SAGE_SRC/doc"
+# export SAGE_SRC="@abs_top_srcdir@/.."
 
 export PATH="$SAGE_LOCAL/bin:$PATH"
 
@@ -382,8 +387,7 @@ export PKG_CONFIG_PATH
 # Whenever a flag like SAGE64 has been set once, it needs to be
 # restored in every run of sage, as mixing 64-bit and 32-bit code is
 # bad idea at best.
-SAGE64=@SAGE64@
-export SAGE64
+# put a file into $SAGE_ETC/env.d to set SAGE64.
 
 ############ compilation flags
 
