sage-bin: sage.in
- config files to @SAGE_ETC@
- cleanup
- PIPESTATUS_CMD

diff --git a/src/bin/sage.in b/src/bin/sage.in
--- a/src/bin/sage.in
+++ b/src/bin/sage.in
@@ -1,8 +1,11 @@
 #!/usr/bin/env bash
 
+# FIXME: move to a reasonable location. better use PATH
+PIPESTATUS_CMD="@abs_top_srcdir@/../../build/pipestatus"
+
 usage() {
     echo "----------------------------------------------------------------------"
-    grep -i version "$SAGE_LOCAL/bin/sage-banner"
+    grep -i version "$SAGE_ETC/sage-banner"
     echo "----------------------------------------------------------------------"
     echo
     ####  1.......................26..................................................78
@@ -35,7 +38,6 @@ usage() {
     echo "                           --long - include lines with the phrase 'long time'"
     echo "                           --verbose - print debugging output during the test"
     echo "                           --optional - controls which optional tests are run"
-    echo "                           --sagenb - test all sagenb files"
     echo "                           --help - show all testing options"
     echo "  -upgrade [url]      -- download, build and install standard packages from"
     echo "                         given url.  If url not given, automatically selects a"
@@ -47,7 +49,7 @@ usage() {
 
 usage_advanced() {
     echo "----------------------------------------------------------------------"
-    grep -i version "$SAGE_LOCAL/bin/sage-banner"
+    grep -i version "$SAGE_ETC/sage-banner"
     echo "----------------------------------------------------------------------"
     echo
     ####  1.......................26..................................................78
@@ -163,7 +165,6 @@ usage_advanced() {
     echo "                           --initial - only show the first failure per block"
     echo "                           --debug - drop into PDB after an unexpected error"
     echo "                           --failed - only test files that failed last test"
-    echo "                           --sagenb - test all sagenb files"
     echo "                           --help - show all testing options"
     echo "  -tp <N> [...]       -- like -t above, but tests in parallel using N threads"
     echo "                         with 0 interpreted as a sensible default"
@@ -233,7 +234,7 @@ usage_advanced() {
     exit 0
 }
 
-# Check for '--nodotsage' before sourcing sage-env; otherwise sage-env
+# Check for '--nodotsage' before sourcing env.sh; otherwise env.sh
 # will already have set some environment variables with the old
 # setting for DOT_SAGE.
 if [ "$1" = '--nodotsage' ]; then
@@ -254,9 +255,9 @@ SAGE_ETC=${SAGE_ETC:-@SAGE_ETC@}
 # fi
 
 # Make sure this doesn't produce output (in case we use this in scripts).
-. "$0-env" >&2
+. "$SAGE_ETC/env.sh" >&2
 if [ $? -ne 0 ]; then
-    echo >&2 "Error setting environment variables by sourcing '$SAGE_ROOT/spkg/bin/sage-env';"
+    echo >&2 "Error setting environment variables by sourcing '$SAGE_ETC/env.sh';"
     echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
     exit 1
 fi
@@ -274,23 +275,26 @@ fi
 
 # Prepare for running Sage, either interactively or non-interactively.
 sage_setup() {
+
+    # FIXME: this check doesn't really make sense.
     # Check that we're not in a source tarball which hasn't been built yet (#13561).
-    if [ ! -f "$SAGE_ROOT/src/sage/all.pyc" ]; then
-        echo >&2 '************************************************************************'
-        echo >&2 'It seems that you are attempting to run Sage from an unpacked source'
-        echo >&2 'tarball, but you have not compiled it yet (or maybe the build has not'
-        echo >&2 'finished). You should run `make` in the Sage root directory first.'
-        echo >&2 'If you did not intend to build Sage from source, you should download'
-        echo >&2 'a binary tarball instead. Read README.txt for more information.'
-        echo >&2 '************************************************************************'
-        exit 1
-    fi
+    # if [ ! -f "$SAGE_ROOT/src/sage/all.pyc" ]; then
+    #     echo >&2 '************************************************************************'
+    #     echo >&2 'It seems that you are attempting to run Sage from an unpacked source'
+    #     echo >&2 'tarball, but you have not compiled it yet (or maybe the build has not'
+    #     echo >&2 'finished). You should run `make` in the Sage root directory first.'
+    #     echo >&2 'If you did not intend to build Sage from source, you should download'
+    #     echo >&2 'a binary tarball instead. Read README.txt for more information.'
+    #     echo >&2 '************************************************************************'
+    #     exit 1
+    # fi
 
     # Display the startup banner
     if [ "$SAGE_BANNER" != "no" ]; then
-        cat "$SAGE_LOCAL/bin/sage-banner"
+        cat "$SAGE_ETC/sage-banner"
     fi
 
+    return # for now
     maybe_sage_location
 
     if [ ! -d "$IPYTHONDIR" ]; then
@@ -299,6 +303,8 @@ sage_setup() {
         # exist, ipython complains.
         mkdir -p "$DOT_SAGE"
     fi
+
+    # BUG: suppressing error messages :(
     sage-cleaner &>/dev/null &
 }
 
@@ -307,13 +313,17 @@ sage_setup() {
 # change various hardcoded paths.  Skip this if we don't have write
 # access to $SAGE_LOCAL (e.g. when running as a different user) or
 # if Python and sage-location haven't been installed yet.
+
+# this must be part of sage-the-distribution
+
 maybe_sage_location()
 {
-    if [ -w "$SAGE_LOCAL" ]; then
-        if [ -x "$SAGE_LOCAL/bin/python" ] && [ -x "$SAGE_LOCAL/bin/sage-location" ]; then
-            sage-location || exit $?
-        fi
-    fi
+#     if [ -w "$SAGE_LOCAL" ]; then
+#         if [ -x "$SAGE_LOCAL/bin/python" ] && [ -x "@prefix@/bin/sage-location" ]; then
+#             sage-location || exit $?
+#         fi
+#     fi
+:
 }
 
 
@@ -349,7 +359,7 @@ if [ "$1" = '-v' -o "$1" = '-version' -o "$1" = '--version' ]; then
     # Workaround for OSX, see http://trac.sagemath.org/15072
     export LC_ALL=C
     exec sed -n -e 's/.*\(Sage Version.*Date: [0-9-]*\).*/\1/p' \
-        "$SAGE_LOCAL"/bin/sage-banner
+        "$SAGE_ETC/sage-banner"
 fi
 
 if [ "$1" = '-root'  -o "$1" = '--root' ]; then
@@ -361,99 +371,22 @@ fi
 # Run Sage's versions of the standard Algebra/Geometry etc. software
 #####################################################################
 
-if [ "$1" = '-axiom' -o "$1" = '--axiom' ]; then
-    shift
-    exec axiom "$@"
-fi
-
-if [ "$1" = '-combinat' -o "$1" = '--combinat' ]; then
-    shift
-    exec sage-combinat "$@"
-fi
-
-if [ "$1" = '-gap' -o "$1" = '--gap' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/gap" "$@"
-fi
-
-if [ "$1" = '-gp' -o "$1" = '--gp' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/gp" "$@"
-fi
-
-if [ "$1" = '-singular' -o "$1" = '--singular' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/singular" "$@"
-fi
-
-if [ "$1" = '-sqlite3' -o "$1" = '--sqlite3' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/sqlite3" "$@"
-fi
-
-if [ "$1" = '-sws2rst' -o "$1" = '--sws2rst' ]; then
-    shift
-    exec sage-sws2rst "$@"
-fi
-
-if [ "$1" = '-twistd' -o "$1" = '--twistd' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/twistd" "$@"
-fi
-
-if [ "$1" = '-ecl' -o "$1" = '--ecl' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ecl" "$@"
-fi
-
-if [ "$1" = '-lisp' -o "$1" = '--lisp' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ecl" "$@"
-fi
-
-if [ "$1" = '-kash' -o "$1" = '--kash' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/kash" "$@"
-fi
+arg=${1/--/-}
+case $arg in
+    -axiom|-combinat|-gap|-gp|-singular|-sqlite3|-twistd|-ecl|\
+    -kash|-maxima|-mwrank|-M2|-scons|-python|-ipython|-R)
+        shift
+        exec "${arg#-}" "$@"
+    ;;
+    -lisp)
+        shift
+        exec "ecl" "$@"
+    ;;
+esac
 
 if [ "$1" = '-fixdoctests' -o "$1" = '--fixdoctests' ]; then
     shift
     exec sage-fixdoctests "$@"
-fi
-
-if [ "$1" = '-maxima' -o "$1" = '--maxima' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/maxima" "$@"
-fi
-
-if [ "$1" = '-mwrank' -o "$1" = '--mwrank' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/mwrank" "$@"
-fi
-
-if [ "$1" = '-M2' -o "$1" = '--M2' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/M2" "$@"
-fi
-
-if [ "$1" = '-scons' -o "$1" = '--scons' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/scons" "$@"
-fi
-
-if [ "$1" = '-python' -o "$1" = '--python' ]; then
-    shift
-    exec python "$@"
-fi
-
-if [ "$1" = '-R' -o "$1" = '--R' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/R" "$@"
-fi
-
-if [ "$1" = '-ipython' -o "$1" = '--ipython' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ipython" "$@"
 fi
 
 if [ "$1" = '-sh' -o "$1" = '--sh' ]; then
@@ -779,7 +712,7 @@ install() {
         PKG_NAME=`echo "$PKG" | sed -e "s/\.spkg$//"`
         PKG_NAME=`basename "$PKG_NAME"`
 
-        "$SAGE_ROOT"/build/pipestatus \
+        $PIPESTATUS_CMD \
             "sage-spkg $OPTINFO $OPTF $OPTS $OPTC '$PKG' 2>&1" \
             "(trap '' SIGINT; tee -a '$SAGE_ROOT/logs/install.log' '$SAGE_LOGS/$PKG_NAME.log')"
         # Do not try to install further packages if one failed
@@ -844,6 +777,7 @@ fi
 if [ "$1" = '-sdist' -o "$1" = "--sdist" ]; then
     maybe_sage_location
     shift
+    maybe_sage_location
     exec sage-sdist "$@"
 fi
 
@@ -857,8 +791,9 @@ if [ "$1" = '-rsyncdist' -o "$1" = "--rsyncdist" ]; then
 fi
 
 if [ "$1" = '-bdist' -o "$1" = "--bdist" ]; then
-    maybe_sage_location
+    # maybe_sage_location, later
     shift
+    maybe_sage_location
     exec sage-bdist "$@"
 fi
 
@@ -884,16 +819,17 @@ if [ "$1" = "-docbuild" -o "$1" = "--docbuild" ]; then
     exec python "$SAGE_DOC_SRC/common/builder.py" "$@"
 fi
 
+# FIXME: move sage-gdb-commands to SAGE_ETC
 if [ "$1" = '-gdb' -o "$1" = "--gdb" ]; then
     shift
     sage_setup
     if [ "$SAGE_DEBUG" = "no" ]; then
         gdb -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python `which sage-ipython` "$@" -i
     else
-        cygdb "$SAGE_SRC/build" "$SAGE_SRC/sage" \
+        cygdb "$SAGE_ROOT/src" "$SAGE_SRC/sage" \
             -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python `which sage-ipython` "$@" -i
     fi
     exit $?
 fi
@@ -957,3 +893,5 @@ if [ $# -ge 1 ]; then
     unset TERM  # See Trac #12263
     exec sage-run "$@"
 fi
+
+# vim:et:sw=4:
