sage-bin: sage.in
- config files to SAGE_ETC=@sysconfdir@
- cleanup

diff --git a/src/bin/sage.in b/src/bin/sage.in
--- a/src/bin/sage.in
+++ b/src/bin/sage.in
@@ -2,7 +2,7 @@
 
 usage() {
     echo "----------------------------------------------------------------------"
-    grep -i version "$SAGE_LOCAL/bin/sage-banner"
+    grep -i version "$SAGE_ETC/sage-banner"
     echo "----------------------------------------------------------------------"
     echo
     ####  1.......................26..................................................78
@@ -35,7 +35,6 @@ usage() {
     echo "                           --long - include lines with the phrase 'long time'"
     echo "                           --verbose - print debugging output during the test"
     echo "                           --optional - controls which optional tests are run"
-    echo "                           --sagenb - test all sagenb files"
     echo "                           --help - show all testing options"
     echo "  -upgrade [url]      -- download, build and install standard packages from"
     echo "                         given url.  If url not given, automatically selects a"
@@ -47,7 +46,7 @@ usage() {
 
 usage_advanced() {
     echo "----------------------------------------------------------------------"
-    grep -i version "$SAGE_LOCAL/bin/sage-banner"
+    grep -i version "$SAGE_ETC/sage-banner"
     echo "----------------------------------------------------------------------"
     echo
     ####  1.......................26..................................................78
@@ -163,7 +162,6 @@ usage_advanced() {
     echo "                           --initial - only show the first failure per block"
     echo "                           --debug - drop into PDB after an unexpected error"
     echo "                           --failed - only test files that failed last test"
-    echo "                           --sagenb - test all sagenb files"
     echo "                           --help - show all testing options"
     echo "  -tp <N> [...]       -- like -t above, but tests in parallel using N threads"
     echo "                         with 0 interpreted as a sensible default"
@@ -231,7 +229,7 @@ usage_advanced() {
     exit 0
 }
 
-# Check for '--nodotsage' before sourcing sage-env; otherwise sage-env
+# Check for '--nodotsage' before sourcing env.sh; otherwise env.sh
 # will already have set some environment variables with the old
 # setting for DOT_SAGE.
 if [ "$1" = '--nodotsage' ]; then
@@ -243,10 +241,18 @@ if [ "$1" = '--nodotsage' ]; then
     exit $status
 fi
 
+SAGE_ETC=${SAGE_ETC:-@sysconfdir@}
+
+if [ ! -f "$SAGE_ETC/env.sh" ]; then
+    echo "cannot locate environment"
+    exit 1
+fi
+
+
 # Make sure this doesn't produce output (in case we use this in scripts).
-. "$0-env" >&2
+. "$SAGE_ETC/env.sh" >&2
 if [ $? -ne 0 ]; then
-    echo >&2 "Error setting environment variables by sourcing '$SAGE_ROOT/spkg/bin/sage-env';"
+    echo >&2 "Error setting environment variables by sourcing '$SAGE_ETC/env.sh';"
     echo >&2 "possibly contact sage-devel (see http://groups.google.com/group/sage-devel)."
     exit 1
 fi
@@ -264,6 +270,9 @@ fi
 
 # Prepare for running Sage, either interactively or non-interactively.
 sage_setup() {
+#    echo "skipping sage-setup (for now)" >&2
+    return
+
     # Check that we're not in a source tarball which hasn't been built yet (#13561).
     if [ ! -d "$SAGE_LOCAL/lib/python/site-packages/sage" ]; then
         echo >&2 '************************************************************************'
@@ -278,7 +287,7 @@ sage_setup() {
 
     # Display the startup banner
     if [ "$SAGE_BANNER" != "no" ]; then
-        cat "$SAGE_LOCAL/bin/sage-banner"
+        cat "$SAGE_LOCAL/etc/sage-banner"
     fi
 
     maybe_sage_location
@@ -289,6 +298,8 @@ sage_setup() {
         # exist, ipython complains.
         mkdir -p "$DOT_SAGE"
     fi
+
+    # BUG: suppressing error messages :(
     sage-cleaner &>/dev/null &
 }
 
@@ -300,7 +311,7 @@ sage_setup() {
 maybe_sage_location()
 {
     if [ -w "$SAGE_LOCAL" ]; then
-        if [ -x "$SAGE_LOCAL/bin/python" ] && [ -x "$SAGE_LOCAL/bin/sage-location" ]; then
+        if [ -x "$SAGE_LOCAL/bin/python" ] && [ -x "@prefix@/bin/sage-location" ]; then
             sage-location || exit $?
         fi
     fi
@@ -337,7 +348,7 @@ fi
 
 if [ "$1" = '-v' -o "$1" = '-version' -o "$1" = '--version' ]; then
     exec sed -n -e '/Version/s/^[ |]\{1,\}//;/Version/s/[ |]\{1,\}$//p' \
-        "$SAGE_LOCAL"/bin/sage-banner
+        "$SAGE_LOCAL"/etc/sage-banner
 fi
 
 if [ "$1" = '-root'  -o "$1" = '--root' ]; then
@@ -349,94 +360,22 @@ fi
 # Run Sage's versions of the standard Algebra/Geometry etc. software
 #####################################################################
 
-if [ "$1" = '-axiom' -o "$1" = '--axiom' ]; then
-    shift
-    exec axiom "$@"
-fi
-
-if [ "$1" = '-combinat' -o "$1" = '--combinat' ]; then
-    shift
-    exec sage-combinat "$@"
-fi
-
-if [ "$1" = '-gap' -o "$1" = '--gap' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/gap" "$@"
-fi
-
-if [ "$1" = '-gp' -o "$1" = '--gp' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/gp" "$@"
-fi
-
-if [ "$1" = '-singular' -o "$1" = '--singular' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/singular" "$@"
-fi
-
-if [ "$1" = '-sqlite3' -o "$1" = '--sqlite3' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/sqlite3" "$@"
-fi
-
-if [ "$1" = '-twistd' -o "$1" = '--twistd' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/twistd" "$@"
-fi
-
-if [ "$1" = '-ecl' -o "$1" = '--ecl' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ecl" "$@"
-fi
-
-if [ "$1" = '-lisp' -o "$1" = '--lisp' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ecl" "$@"
-fi
-
-if [ "$1" = '-kash' -o "$1" = '--kash' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/kash" "$@"
-fi
+arg=${1/--/-}
+case $arg in
+    -axiom|-combinat|-gap|-gp|-singular|-sqlite3|-twistd|-ecl|\
+    -kash|-maxima|-mwrank|-M2|-scons|-python|-ipython|-R)
+        shift
+        exec "@JUST_SAGE_LOCAL_BIN@${arg#-}" "$@"
+    ;;
+    -lisp)
+        shift
+        exec "@JUST_SAGE_LOCAL_BIN@ecl" "$@"
+    ;;
+esac
 
 if [ "$1" = '-fixdoctests' -o "$1" = '--fixdoctests' ]; then
     shift
     exec sage-fixdoctests "$@"
-fi
-
-if [ "$1" = '-maxima' -o "$1" = '--maxima' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/maxima" "$@"
-fi
-
-if [ "$1" = '-mwrank' -o "$1" = '--mwrank' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/mwrank" "$@"
-fi
-
-if [ "$1" = '-M2' -o "$1" = '--M2' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/M2" "$@"
-fi
-
-if [ "$1" = '-scons' -o "$1" = '--scons' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/scons" "$@"
-fi
-
-if [ "$1" = '-python' -o "$1" = '--python' ]; then
-    shift
-    exec python "$@"
-fi
-
-if [ "$1" = '-R' -o "$1" = '--R' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/R" "$@"
-fi
-
-if [ "$1" = '-ipython' -o "$1" = '--ipython' ]; then
-    shift
-    exec "$SAGE_LOCAL/bin/ipython" "$@"
 fi
 
 if [ "$1" = '-sh' -o "$1" = '--sh' ]; then
@@ -826,6 +765,7 @@ fi
 
 if [ "$1" = '-sdist' -o "$1" = "--sdist" ]; then
     shift
+    maybe_sage_location
     exec sage-sdist "$@"
 fi
 
@@ -839,12 +779,8 @@ if [ "$1" = '-rsyncdist' -o "$1" = "--rsyncdist" ]; then
 fi
 
 if [ "$1" = '-bdist' -o "$1" = "--bdist" ]; then
-    if [ $# -ne 2 ]; then
-        echo >&2 "** MISSING VERSION NUMBER! **"
-        exit 2
-    fi
-    maybe_sage_location
     shift
+    maybe_sage_location
     exec sage-bdist "$@"
 fi
 
@@ -870,16 +806,17 @@ if [ "$1" = "-docbuild" -o "$1" = "--docbuild" ]; then
     exec python "$SAGE_DOC/common/builder.py" "$@"
 fi
 
+# FIXME: move sage-gdb-commands to SAGE_ETC
 if [ "$1" = '-gdb' -o "$1" = "--gdb" ]; then
     shift
     sage_setup
     if [ "$SAGE_DEBUG" = "no" ]; then
         gdb -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python `which sage-ipython` "$@" -i
     else
-        cygdb "$SAGE_SRC/build" "$SAGE_SRC/sage" \
+        cygdb "$SAGE_ROOT/src" "$SAGE_SRC/sage" \
             -x "$SAGE_LOCAL/bin/sage-gdb-commands" \
-            -args python "$SAGE_LOCAL/bin/sage-ipython" "$@" -i
+            -args python `which sage-ipython` "$@" -i
     fi
     exit $?
 fi
@@ -943,3 +880,5 @@ if [ $# -ge 1 ]; then
     unset TERM  # See Trac #12263
     exec sage-run "$@"
 fi
+
+# vim:et:sw=4:
